package com.whiteCollar.shops.controller;

import com.whiteCollar.shops.data.Shops;
import com.whiteCollar.shops.data.ShopsRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/shops") // This means URL's start with /demo (after Application path)
public class ShopsController
{
    @Autowired // This means to get the bean called shopsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ShopsRepository shopsRepository;
    private String SubmitMessage = "";

    @PostMapping
    //@ResponseBody
    public String addNewShop (@RequestParam String name , @RequestParam int capacity, Model model)
    {
        //http://localhost:8080/add?name="TheWhiteCollarShop"&capacity=20
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if ( (name != "") && (capacity!= 0) )
        {
            //buscamos una tienda con ese nombre
            List<Shops> foundShops = shopsRepository.findByNameIgnoreCase(name);
            if ( foundShops.size() > 0)
            {
                SubmitMessage = "The Shop already Existed";
                return ( shopHome( model ) );
            }
            Shops shop = new Shops();
            shop.setName(name);
            shop.setCapacity(capacity);
            shopsRepository.save(shop);
        }
        SubmitMessage = "Shop Saved";
        return ( shopHome( model ) );
    }

    @GetMapping
    public String shopHome(Model model)
    {
        model.addAttribute("message", SubmitMessage);
        SubmitMessage = "";
        List<Shops> shops = new ArrayList<>();
        shopsRepository.findAll().forEach(i -> shops.add(i));
        model.addAttribute("ShopsList", shops);
        return "shops";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Shops> getAllShops() {
        // This returns a JSON or XML with the shops
        return shopsRepository.findAll();
    }

}
