package com.whiteCollar.shops.controller;

import com.whiteCollar.shops.data.Shops;
import com.whiteCollar.shops.data.ShopsRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/shops") // This means URL's start with /demo (after Application path)

public class ShopsController
{
    @Autowired // This means to get the bean called shopsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ShopsRepository shopsRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewShop (@RequestParam String name , @RequestParam int capacity)
    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Shops shop = new Shops();
        shop.setName(name);
        shop.setCapacity(capacity);
        shopsRepository.save(shop);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Shops> getAllShops() {
        // This returns a JSON or XML with the shops
        return shopsRepository.findAll();
    }
}
